services:
  database:
    container_name: digiproc_database
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: digiproc
    ports:
      - "5432:5432"
    restart: always
